In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [13]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.1529083 , -0.48509756,  0.6104205 , -0.12841657,  0.23093933,
        -0.6087346 , -0.25397676, -0.3881294 ,  0.10649051, -0.00662404]],
      dtype=float32)

In [14]:
model(x_train[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-0.1529083 , -0.48509756,  0.6104205 , -0.12841657,  0.23093933,
        -0.6087346 , -0.25397676, -0.3881294 ,  0.10649051, -0.00662404]],
      dtype=float32)>

In [15]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [17]:
loss_fn(y_train[:1], predictions).numpy()

2.8661299

In [21]:
-tf.math.log(1/10)

<tf.Tensor: shape=(), dtype=float32, numpy=2.3025851>

#### Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [24]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

#### Use the Model.fit method to adjust your model parameters and minimize the loss

In [25]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2959 - accuracy: 0.9144
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1456 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1075 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0885 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0762 - accuracy: 0.9761


#### The Model.evaluate method checks the model's performance, usually on a validation set or test set. 

In [26]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0719 - accuracy: 0.9779 - 360ms/epoch - 1ms/step


[0.07186076790094376, 0.9779000282287598]

To return a probability, wrap the trained model, and attach the softmax to it.

In [28]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.73989283e-08, 2.54374011e-09, 2.01915391e-05, 2.36586566e-05,
        6.55179307e-14, 3.34261365e-08, 5.46906982e-15, 9.99943256e-01,
        8.65152927e-08, 1.27664534e-05],
       [3.62107344e-10, 5.31133410e-05, 9.99944687e-01, 1.41348551e-06,
        3.88991527e-18, 1.98039331e-07, 3.83162356e-11, 6.88695683e-13,
        5.89303795e-07, 1.39727605e-14],
       [3.17207338e-07, 9.97720063e-01, 5.40067209e-04, 3.73137436e-06,
        2.08031452e-05, 6.86579097e-06, 6.98716321e-05, 7.33573281e-04,
        9.03016422e-04, 1.64868266e-06],
       [9.99762475e-01, 8.85580997e-10, 1.62571145e-04, 1.87507645e-08,
        1.43387138e-06, 2.98850728e-06, 4.06306171e-05, 1.56393162e-05,
        7.47229763e-08, 1.41713317e-05],
       [7.08325433e-06, 2.66634412e-08, 1.09580695e-04, 7.51443565e-08,
        9.93147075e-01, 9.36785739e-07, 3.27253929e-06, 1.38653180e-04,
        1.07321766e-05, 6.58256235e-03]], dtype=float32)>